import re

# Count how many choruses, refrains or hooks are in a song.
def num_of_choruses(text):
    # Pattern generated by chatgpt
    pattern1 = re.compile(r'\[(refrain|chorus|hook).*\]\s*[x\*](\d+)', re.IGNORECASE)
    pattern2 = re.compile(r'\[(refrain|chorus|hook)\s*([^]]*)\s*[x\*]\s*(\d+)\]', re.IGNORECASE)
    pattern3 = re.compile(r'\[(refrain|chorus|hook)\s*([^\[\]x*]*?)\](?!\s*[x*]\s*\d+)', re.IGNORECASE)
    total_count = 0
    
    for match in pattern1.finditer(text):
        # Determine the multiplier value
        if match.group(2):
            # Multiplier in the format [keyword (random text)] x2 or [keyword (random text)] *2
            multiplier = match.group(2)
        
        if multiplier:
            count = int(multiplier)
            total_count += count
        
    
    for match in pattern2.finditer(text):
        # Determine the multiplier value
        if match.group(3):
            # Multiplier in the format [keyword (random text) x2]  or [keyword (random text) *2] 
            multiplier = match.group(3)
        
        if multiplier:
            count = int(multiplier)
            total_count += count
        
    # There is no multiplier so the entry is in the format [keyword (random text)]
    no_multipliers = len(pattern3.findall(text))
    total_count = no_multipliers + total_count
    
    return total_count